/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiStudioRouteImport } from './routes/ai-studio'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RendersRouteImport } from './routes/renders'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiStudioRoute = AiStudioRouteImport.update({
  id: '/ai-studio',
  path: '/ai-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RendersRoute = RendersRouteImport.update({
  id: '/renders',
  path: '/renders',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/assets': typeof AssetsRoute
  '/projects': typeof ProjectsRoute
  '/renders': typeof RendersRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/assets': typeof AssetsRoute
  '/projects': typeof ProjectsRoute
  '/renders': typeof RendersRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/assets': typeof AssetsRoute
  '/projects': typeof ProjectsRoute
  '/renders': typeof RendersRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/ai-studio' | '/assets' | '/projects' | '/renders' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-studio' | '/assets' | '/projects' | '/renders' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/ai-studio'
    | '/assets'
    | '/projects'
    | '/renders'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiStudioRoute: typeof AiStudioRoute
  AssetsRoute: typeof AssetsRoute
  ProjectsRoute: typeof ProjectsRoute
  RendersRoute: typeof RendersRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-studio': {
      id: '/ai-studio'
      path: '/ai-studio'
      fullPath: '/ai-studio'
      preLoaderRoute: typeof AiStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renders': {
      id: '/renders'
      path: '/renders'
      fullPath: '/renders'
      preLoaderRoute: typeof RendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiStudioRoute: AiStudioRoute,
  AssetsRoute: AssetsRoute,
  ProjectsRoute: ProjectsRoute,
  RendersRoute: RendersRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
